title: Devops Agent Team
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://furkannzmnn.github.io/devops-agent

aux_links:
  Template Repository: https://github.com/furkannzmnn/devops-agent
